### ISSUE TITLE
Finding sections and notes after clicking help

### ISSUE THREAD

**Issue by KnowledgeGarden** [MicroPad/MicroPad-Electron#1]
Clicking Help clears the screen. Clicking Exit Full Screen takes you back to the original Help sidebar, but without a list of your sections. The Notepads Menu does not list my sections. What am I missing?

**Comment by NickGeek** [comment]
Clicking Help opens the Help notepad (hence clearing the screen) your section list is on the sidebar.

**Comment by KnowledgeGarden** [comment]
But, the sidebar is empty. At one point, I had a section, with a note with one text and one image. They disappeared.

**Comment by KnowledgeGarden** [comment]
While we are here,  where would I look for the data file (macbook)?

**Comment by NickGeek** [comment]
There's a "notepads" dropdown at the top of the screen, that has a list of your notepads for you to open in it.

I think there are instructional videos showing that.

**Comment by NickGeek** [comment]
Data is stored in IndexedDB, the easiest way to get that out would be to hit Command+S with the notepad open, or click the "Export All" button in the notepad-dropdown.

**Comment by KnowledgeGarden** [comment]
Thank you!

**Comment by alemangui** [comment]
@KnowledgeGarden did you manage to get them back? I have the same problem, they are not on the "Notepads" section nor on the Export files.

**Comment by NickGeek** [comment]
@alemangui What browser/device and what do you see if you click the "notebooks" dropdown?

**Comment by alemangui** [comment]
I'm on Linux Ubuntu 18.04. I had two notebooks, both gone after clicking on "Help". In the dropdownI only see the *Help* Notebook (other than the options New, Import, Export, and Connect to µSync).

![image](https://user-images.githubusercontent.com/1225929/57571241-c29c5b80-740b-11e9-9b01-fdecad922ffa.png)

**Comment by NickGeek** [comment]
I'm having trouble replicating that. By notebooks you don't mean the sections you see in the sidebar, like these:
![latest](https://user-images.githubusercontent.com/3462055/57578261-b3d1a980-74dc-11e9-8791-246a8cff11ba.png)
do you?

**Comment by alemangui** [comment]
Hi Nick, sorry for the delay. Yeah I mean those. I had created a new *Section* in that sidebar, but it disappeared. This is what I get after having clicked on "Help":

![image](https://user-images.githubusercontent.com/1225929/57845019-6ea9c200-77d1-11e9-97c6-ab070bb2b883.png)

**Comment by NickGeek** [comment]
@alemangui Ah, I know what happened then.

The Help notebook is replaced with the latest edition when you click the "Help" button, so any edits you made to it (such as adding a new section) would have been overwritten.

I'm going to add an overwrite warning message in the next version of MicroPad that should stop people from inadvertently overwriting their notes (https://github.com/MicroPad/Web/issues/147).

**Comment by NickGeek** [comment]
@alemangui This has been done now (as of v3.18)

**Comment by An-AngryBear** [comment]
@NickGeek This just happened to me. Did not notice the warning message and now all my notes are gone. I think the problem is new users will use the help section, since it's the default section, instead of making a new section. Think it would be smart to not have the help section editable, or to automatically create a new section when the user clicks "+note" or "+section". Pretty disappointed as all my notes from the last year are just gone, with seemingly no way to recover because of a simple east-to-make mistake.

**Comment by NickGeek** [comment]
Hi @An-AngryBear, I'm really sorry to hear about that. Have you ever exported/saved your notebook (Ctrl+S/Cmd+S) to your hard drive? If so we should be able to recover it from there. Additionally, if you have used MicroSync it should be recoverable.

If not then the notes won't be recoverable because they were overwritten when you loaded in the new Help notebook. The current warning looks like this:
![image](https://user-images.githubusercontent.com/3462055/122140940-70f31480-cea0-11eb-8048-a1abf64f04ed.png)

Based on your feedback I'm going to make the notebook read-only and also not open it automatically for new users: https://github.com/MicroPad/MicroPad-Core/issues/357. Is there anything else that you think will be worth doing to make the UX better around the help notebook experience?

**Comment by NickGeek** [comment]
@An-AngryBear The Help notebook is now read-only (as of v3.30)
