### ISSUE TITLE
Where does MicroPad store notebooks?

### ISSUE THREAD

**Issue by derekwilling** [MicroPad/MicroPad-Electron#15]
Can you point micropad to save notes somewhere else? Like a mounted file server or one-drive?

**Comment by NickGeek** [comment]
MicroPad stores notebooks in IndexedDB. You can "export all" (Ctrl+Shift+S) to put all your notepads on your filesystem.

**Comment by derekwilling** [comment]
On windows it looks like the database is stored by default at "%APPDATA%\Roaming\micropad"

At this time it appears there is no way in the GUI or any config files to change the default location for the database storage.

Thanks for the info @NickGeek

**Comment by prawiropanji** [comment]
i love using micropad, @NickGeek is it any possible to embeded inline local image in markdown text?

**Comment by NickGeek** [comment]
@prawiropanji Hi, thanks!

It used to be back in MicroPad Classic but it caused a lot of issues so it wasn't included in v3.

Typically I recommend using lots of elements in your notes instead of trying to have a really long text one. You could then just insert the image below the element and then make another one afterwards.

Alternatively, assuming the image isn't private you could upload it to something like imgur and embed it inline.
