### ISSUE TITLE
Portable App loses Bibliography 

### ISSUE THREAD

**Issue by welpdx** [MicroPad/MicroPad-Electron#34]
Using the portable version of micropad. The bibliography keeps disappearing, esp after switching computers. 
Running the app from a usb. 

Thanks

**Comment by NickGeek** [comment]
Ah, yep. That's because while the app is portable, the notebooks + settings are stored on your computer in `AppData`.

You can hit `Ctrl+S` to save a notebook to the USB stick, and `Ctrl+O` to open one. You can also use MicroSync for free (for mostly-text based notebooks) by clicking the "Connect to μSync" button on the sidebar.

**Comment by NickGeek** [comment]
Ah, I think I've found a bug around bibliography storage even if there is an export. I've raised a case to fix it and it will be out very soon: https://github.com/MicroPad/Notebook-Library/issues/29 is the case for it.

**Comment by NickGeek** [comment]
I have just released v3.21.9, which has fixed the bibliography bug. Thanks for reporting it!

**Comment by welpdx** [comment]
Hey thanks Nick! It's working now! Great Work!

Cheers~



<details>
        <summary>Edit:</summary>
   Forgot to add well deserved praise XD
    </details>
